"use client";

import React, { useState, useTransition } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { isClerkAPIResponseError } from "@clerk/nextjs/errors";
import {
  otpSchema,
  backupCodeSchema,
  type OtpInput,
  type BackupCodeInput,
} from "@/lib/validations/auth";
import { mapClerkErrors } from "@/components/auth/clerk-error-mapping";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export interface OtpVerifyFormProps {
  onVerify: (code: string) => Promise<{ status: string; createdSessionId: string | null }>;
  onSuccess: (sessionId: string) => Promise<void>;
  returnTo: string | null;
  strategy?: "email_code" | "phone_code" | "totp" | "backup_code";
  availableStrategies?: ("email_code" | "phone_code" | "totp" | "backup_code")[];
  onSelectStrategy?: (strategy: "email_code" | "phone_code" | "totp" | "backup_code") => void;
  externalError?: string | null;
}

/**
 * OTP / second factor verification form supporting 6-digit numeric codes and backup codes.
 */
export function OtpVerifyForm({
  onVerify,
  onSuccess,
  strategy = "email_code",
  availableStrategies,
  onSelectStrategy,
  externalError,
}: OtpVerifyFormProps) {
  const [formError, setFormError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();
  const isBackupCode = strategy === "backup_code";
  const displayedError = formError || externalError;

  const {
    register,
    handleSubmit,
    setValue,
    setError,
    formState: { errors, isSubmitting },
  } = useForm<OtpInput | BackupCodeInput>({
    resolver: zodResolver(isBackupCode ? backupCodeSchema : otpSchema),
    defaultValues: {
      code: "",
    },
  });

  const onSubmit = async (data: OtpInput | BackupCodeInput) => {
    setFormError(null);
    try {
      const result = await onVerify(data.code);
      if (result.status === "complete" && result.createdSessionId) {
        startTransition(async () => {
          try {
            await onSuccess(result.createdSessionId as string);
          } catch {
            setFormError("Failed to activate session. Please try signing in again.");
          }
        });
      } else {
        setFormError(`Unexpected status: ${result.status}`);
      }
    } catch (err) {
      if (isClerkAPIResponseError(err)) {
        mapClerkErrors(err.errors, setError, setFormError);
      } else {
        setFormError("Something went wrong. Please try again.");
      }
    }
  };

  const handleCodeChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (isBackupCode) {
      setValue("code", e.target.value, { shouldValidate: true });
      return;
    }

    const sanitized = e.target.value.replace(/\D/g, "").slice(0, 6);
    setValue("code", sanitized, { shouldValidate: true });
    if (sanitized.length === 6 && !isSubmitting && !isPending) {
      void handleSubmit(onSubmit)();
    }
  };

  const getLabel = () => {
    switch (strategy) {
      case "backup_code":
        return "Backup recovery code";
      case "totp":
        return "Authenticator app code";
      case "phone_code":
        return "SMS verification code";
      case "email_code":
      default:
        return "Email verification code";
    }
  };

  const getStrategyButtonLabel = (strat: "email_code" | "phone_code" | "totp" | "backup_code") => {
    switch (strat) {
      case "totp":
        return "Use Authenticator app (TOTP)";
      case "phone_code":
        return "Send code via SMS";
      case "email_code":
        return "Send code via Email";
      case "backup_code":
        return "Use emergency backup recovery code";
    }
  };

  return (
    <div className="space-y-6">
      <div className="space-y-2 text-center">
        <h1 className="text-2xl font-bold tracking-tight text-primary">Two-Factor Authentication</h1>
        <p className="text-sm text-muted">
          {isBackupCode
            ? "Enter one of your emergency recovery backup codes."
            : "Enter the code sent to your device or generated by your authenticator."}
        </p>
      </div>

      <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
        <div className="space-y-2">
          <label htmlFor="code" className="block text-sm font-medium text-primary">
            {getLabel()}
          </label>
          <Input
            id="code"
            type="text"
            inputMode={isBackupCode ? "text" : "numeric"}
            autoComplete={isBackupCode ? "off" : "one-time-code"}
            maxLength={isBackupCode ? 32 : 6}
            disabled={isSubmitting || isPending}
            placeholder={isBackupCode ? "e.g. 1a2b-3c4d-5e6f" : "123456"}
            className="text-center font-mono text-lg tracking-widest"
            {...register("code")}
            onChange={handleCodeChange}
          />
          {errors.code && (
            <p role="alert" className="text-sm text-state-error">
              {errors.code.message}
            </p>
          )}
        </div>

        {displayedError && (
          <p role="alert" className="text-sm text-state-error">
            {displayedError}
          </p>
        )}

        <Button
          type="submit"
          disabled={isSubmitting || isPending}
          className="w-full bg-accent-primary text-base font-semibold hover:bg-accent-primary/90"
        >
          {isSubmitting || isPending ? "Verifying…" : "Verify code"}
        </Button>
      </form>

      {availableStrategies && availableStrategies.length > 1 && onSelectStrategy && (
        <div className="pt-2 text-center space-y-2">
          {availableStrategies
            .filter((s) => s !== strategy)
            .map((altStrategy) => (
              <div key={altStrategy}>
                <button
                  type="button"
                  onClick={() => onSelectStrategy(altStrategy)}
                  className="text-xs text-accent-primary hover:underline"
                >
                  {getStrategyButtonLabel(altStrategy)}
                </button>
              </div>
            ))}
        </div>
      )}
    </div>
  );
}
